puts "The students of March 2014 cohort at Makers Academy"
puts "---------------------"
puts "Josh Fail-Brown"
puts "Steve Musgrave"
puts "Sroop Sunar"
puts "Colin Marshall"
puts "Louise Lai"
puts "Robin Doble"
puts "Alex Wong"
puts "Scott Dimmock"
puts "Muhanad Al-Rubaiee"
puts "Shelley Hope"
puts "Will Hall"
puts "Oliver Delevingne"
puts "Nico"
puts "Apostolis"
puts "Stefania"
puts "Robert Leon"
puts "Emma Williams"
puts "Joey Wolf"
puts "Julie Walker"